### ISSUE TITLE
MARKETPLACE: Review Publisher Content for Accuracy / Improvements

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_marketplace#27]
Kristine, because you have spent so much time in the tools, I think you'd be best for this. And I think they can be improved. Let me know if I can help.

- [x] Review Website Publisher
- [x] Review Wiki Publisher
- [x] Review Blog Publisher

on www_threefold_marketplace

**Comment by Vilnite** [comment]
I tweaked it a bit but not much I can provide regards deployment process or technical comparisons which is the most interesting thing people will wanna know here. Why this instead of Wordpress or Mobirise for example.

For blog, websites, wikis it's the same tool so of course description is the same.
