### ISSUE TITLE
TF MARKETPLACE - product cards on apps page needs to be clickable

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_marketplace#6]
- [x] Please make them clickable
<img width="1390" alt="Screenshot 2021-02-17 at 12 15 49" src="https://user-images.githubusercontent.com/20182572/108197572-39a76d80-7123-11eb-8903-f4aafa189886.png">

- [x] When click on card it should open a markdown page

- [x] Markdown page should show content that is provided for each card in `all_apps/../index.md`
<img width="542" alt="Screenshot 2021-02-17 at 13 22 17" src="https://user-images.githubusercontent.com/20182572/108197518-2c8a7e80-7123-11eb-8948-4b18ca865b6a.png">

**Comment by Vilnite** [comment]
Doesn't work.
I added all apps, please make sure descriptions are linked, apps are clickable and description page opens in the same tab.

**Comment by samaradel** [comment]
it still works on staging but not in development because you changed the ids you provide [15d673](https://github.com/threefoldfoundation/www_threefold_marketplace/commit/15d673fb7fed2d7a97d900d7f647045a39c735a1#diff-b486ad26ec9281e7bbc2c72fac995d346f3679a036d556aaa04fec1182cbc008R2) 
![image](https://user-images.githubusercontent.com/11662805/108625603-7d1c1780-7454-11eb-82b3-40fca204c81b.png)

 please make sure when you change any id that it's not involved in any process.
